; Global settings shared across all configurations
[env]
platform = espressif32
board = waveshare_esp32_s3_zero
monitor_filters = esp32_exception_decoder
framework = espidf
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
monitor_port = COM6
board_build.partitions = partitions.csv

; Configuration for Board 1: Master (Central Hub with Display)
[env:master_node]
build_flags = 
    -D ROLE_MASTER
    -D PROTOCOL_CAN
;    -D PROTOCOL_I2C
;    -D PROTOCOL_I2S
;    -D PROTOCOL_SPI
;    -D PROTOCOL_UART
upload_port = COM8

; Configuration for Board 2: Slave 1 
[env:slave_env]
build_flags = 
    -D ROLE_SLAVE_ENV
    -D PROTOCOL_CAN
;    -D PROTOCOL_I2C
;    -D PROTOCOL_I2S
;    -D PROTOCOL_SPI
;    -D PROTOCOL_UART
; upload_protocol = custom
; upload_port = COM8
; extra_scripts = upload_can.py

; Configuration for Board 3: Slave 2
[env:slave_motion]
build_flags = 
    -D ROLE_SLAVE_MOTION
    -D PROTOCOL_CAN
;    -D PROTOCOL_I2C
;    -D PROTOCOL_I2S
;    -D PROTOCOL_SPI
;    -D PROTOCOL_UART
; upload_protocol = custom
; upload_port = COM8
; extra_scripts = upload_can.py
